spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/wx
    username: root
    password: Hu@670911
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
request:
  encrykey: abcdefgabcdefg12
  appid: 12331313
  secretcode: 32qweqweq
  granttype: authorization_code
  openidurl: https://api.weixin.qq.com/sns/jscode2session
  postoidurl: https://www.s3.com/s3serv
logging:
  config: classpath:/log/logback-spring.xml
