spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/wx
    username: root
    password: Hu@670911
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
  servlet:
    context-path: /wxpayserv_s3
  tomcat:
    uri-encoding: UTF-8
request:
  appid: lYKjqULk9pZfHrfJcCv3I49z+Aoalw/2rN3hahoO7Lw=
  secretcode: Jj88T7qXUUTZsUbyJj+zfY9UOwlCg0Am0vcmdQr+wG5k2ODJRLBfiOQSaG9223BK
  granttype: authorization_code
  openidurl: https://api.weixin.qq.com/sns/jscode2session
  postoidurl: https://www.s3.com/s3serv
logging:
  config: classpath:/log/logback-spring.xml
